server.port: 6007
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

logging:
  level:
    root: INFO
    com.nguyen: DEBUG